# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
llm:
  api_type: "claude"
  model: "k2p5"
  base_url: "https://api.kimi.com/coding"
  api_key: "sk-kimi-7dMdDQgxULGom1dqqEJY8kv2SFqmSg7JrRlHiIwYq3r3rgwOemQ7v1mKchgJWrmX"
  stream: false
  timeout: 300
